export const FORM_FIELDS = {
  EMAIL: "email",
  PASSWORD: "password",
  NAME: "name",
  ID: "id",
  ACCESS_TOKEN: "accessToken",
  IS_PUBLIC: "isPublic",
  CREATOR_ID: "creatorId",
  TITLE: "title",
  CONTENT: "content",
  DUE_DATE: "dueDate",
  IS_COMPLETED: "isCompleted",
  CATEGORY_ID: "categoryId",
  NOTIFICATION_ID: "notificationId",
  USER_ID: "userId",
  IS_READ: "isRead",
  SENT_AT: "sentAt",
  PAGE: "page",
  SIZE: "size",
  PUSH_TOKEN: "pushToken",
  IMAGE: "image",
  IMAGE_URL: "imageUrl",
};

export const PASSWORD_MIN_LENGTH = 6;
